//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ifmouseraspnet {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm regUser;
		
		protected System.Web.UI.WebControls.TextBox _fname;
		
		protected System.Web.UI.WebControls.TextBox _name;
		
		protected System.Web.UI.WebControls.TextBox _lname;
		
		protected System.Web.UI.WebControls.TextBox _email;
		
		protected System.Web.UI.WebControls.TextBox _login;
		
		protected System.Web.UI.WebControls.TextBox _password;
		
		protected System.Web.UI.WebControls.Button _reg_submit;
		
		protected System.Web.UI.WebControls.Table TableUsers;
	}
}
